### ISSUE TITLE
usage of exclude and include options for database not possible

### ISSUE THREAD

**Issue by nabossha** [webdevops/go-sync#4]
according to this function-call 
https://github.com/webdevops/go-sync/blob/232268d689c415aeffb4f11b0083a3cc3590a2e6/sync/server_sync_database.go#L131

the usage of exclude / include options for syncing a database is not possible since useFilter is always populated with "false".

can this be fixed or is there an undocumented feature to use exlude / include on databse tables?

**Comment by misterboe** [comment]
Same problem here

**Comment by georgringer** [comment]
I patched it manually and changed `false` to `true` and works fine ;)
[gosync-linux-arm.zip](https://github.com/webdevops/go-sync/files/3845694/gosync-linux-arm.zip)
[gosync-linux-arm64.zip](https://github.com/webdevops/go-sync/files/3845695/gosync-linux-arm64.zip)
[gosync-linux-x64.zip](https://github.com/webdevops/go-sync/files/3845697/gosync-linux-x64.zip)
[gosync-osx-x64.zip](https://github.com/webdevops/go-sync/files/3845698/gosync-osx-x64.zip)
[gosync-windows-x64.zip](https://github.com/webdevops/go-sync/files/3845701/gosync-windows-x64.zip)
